<?php

namespace Kodo\ZooBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EspecesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecesRepository extends EntityRepository
{
}
