<?php

namespace Kodo\ZooBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeAlimentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAlimentationRepository extends EntityRepository
{
    public function myFindAll()
    {
        $queryBuilder = $this->createQueryBuilder('a');

        $query = $queryBuilder->getQuery();

        $results = $query->getResult();

        return $results;
    }
}
